---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Generate
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/shlomif/perl-Class-Generate.git
version: 1.13
